// Package db @Description 系统设置的key
// @Author 小游
// @Date 2021/04/10
package db

const (
	// KeyAppImg APP下载二维码
	KeyAppImg = "app_img"
	// KeyH5Img H5客户端二维码
	KeyH5Img = "h5_img"
	// KeyMiniProgramImg 小程序的二维码图片
	KeyMiniProgramImg = "mini_program_img"
	// KeyAppDownloadVersion APP最新版本版本号
	KeyAppDownloadVersion = "app_download_version"
	// KeyAppDownloadDescription APP最新版本更新说明
	KeyAppDownloadDescription = "app_download_description"
	// KeyAppDownloadDownload APP最新版本下载地址
	KeyAppDownloadDownload = "app_download_download"
	// KeyBiBoImg B博界面背景图
	KeyBiBoImg = "bi_bo_img"
	// KeyBiliCookie B站cookie
	KeyBiliCookie = "bili_cookie"
	// KeyBiliShow B站个人认证
	KeyBiliShow = "bili_show"
	// KeyBiliUID B站uid
	KeyBiliUID = "bili_uid"
	// KeyBuildTime 网站创建时间
	KeyBuildTime = "build_time"
	// KeyCommentListCount 评论管理界面评论数
	KeyCommentListCount = "comment_list_count"
	// KeyCommentNum 最近评论显示数目
	KeyCommentNum = "comment_num"
	// KeyBarrageImg 弹幕墙背景图片
	KeyBarrageImg = "barrage_img"
	// KeyDiaryAdminList 日记管理界面日记显示条数
	KeyDiaryAdminList = "diary_admin_list"
	// KeyDiaryDecNum 日记管理界面载要显示字数
	KeyDiaryDecNum = "diary_dec_num"
	// KeyDiaryImg 日记界面背景图片
	KeyDiaryImg = "diary_img"
	// KeyDiaryListCount 日记界面显示日记条数
	KeyDiaryListCount = "diary_list_count"
	// KeyDouBanCookie 豆瓣的cookie信息
	KeyDouBanCookie = "dou_ban_cookie"
	// KeyDouBanImg 我的豆瓣界面背景图片
	KeyDouBanImg = "dou_ban_img"
	// KeyDouBanLastUpdate 我的豆瓣最后更新数据
	KeyDouBanLastUpdate = "dou_ban_last_update"
	// KeyDouBanUser 豆瓣的用户id
	KeyDouBanUser = "dou_ban_user"
	// KeyDouBanListCount 我的豆瓣记录数
	KeyDouBanListCount = "dou_ban_list_count"
	// KeyAnimationImg 我的追番背景图片
	KeyAnimationImg = "animation_img"
	// KeyFriendAvatar 友链头像地址
	KeyFriendAvatar = "friend_avatar"
	// KeyFriendDec 友链描述
	KeyFriendDec = "friend_dec"
	// KeyFriendLink 友链地址
	KeyFriendLink = "friend_link"
	// KeyFriendName 友链名字
	KeyFriendName = "friend_name"
	// KeyFriendImg 友链界面背景图片
	KeyFriendImg = "friend_img"
	// KeyHeadImg 主页顶部图片
	KeyHeadImg = "head_img"
	// KeyAppTopImg 顶部扫描下载APP图片
	KeyAppTopImg = "app_top_img"
	// KeyAppDownloadUrl APP下载网页
	KeyAppDownloadUrl = "app_download_url"
	// KeyIndexImg 主页背景图片
	KeyIndexImg = "index_img"
	// KeyKeyword 网站关键词
	KeyKeyword = "keyword"
	// KeyLoginLogo 登录界面的logo
	KeyLoginLogo = "login_logo"
	// KeyMusicId 网易云歌单id
	KeyMusicId = "music_id"
	// KeyMusicU 网易云用户ID
	KeyMusicU = "music_u"
	// KeyMusicContent 网易云音乐内容
	KeyMusicContent = "music_content"
	// KeyMyAvatar 个人信息卡片头像
	KeyMyAvatar = "my_avatar"
	// KeyMyBackground 个人信息片背景
	KeyMyBackground = "my_background"
	// KeyMyIntroduce 个人信息卡片个人介绍
	KeyMyIntroduce = "my_introduce"
	// KeyMyBiliBili 个人信息卡片B站信息
	KeyMyBiliBili = "my_bili_bili"
	// KeyMyGithub 个人信息卡片github信息
	KeyMyGithub = "my_github"
	// KeyMySteam 个人信息卡片steam信息
	KeyMySteam = "my_steam"
	// KeyMyTelegram 个人信息卡片电报群链接
	KeyMyTelegram = "my_telegram"
	// KeyMyTwitter 个人信息卡片Twitter地址
	KeyMyTwitter = "my_twitter"
	// KeyMyZhiHu 个人信息卡片知乎地址
	KeyMyZhiHu = "my_zhi_hu"
	// KeyDonateImg 赞助界面图片地址
	KeyDonateImg = "donate_img"
	// KeyPostDecCount 文章摘要字数
	KeyPostDecCount = "post_dec_count"
	// KeyPostImg 文章详情界面背景图片
	KeyPostImg = "post_img"
	// KeyPostListCount 主页一页显示文章数
	KeyPostListCount = "post_list_count"
	// KeySiteBeiAn 网站的备案号
	KeySiteBeiAn = "site_bei_an"
	// KeySiteGovBeiAn 公安备案号
	KeySiteGovBeiAn = "site_gov_bei_an"
	// KeySiteDescription 网站的个人信息描述
	KeySiteDescription = "site_description"
	// KeySiteEmail 站长的邮箱
	KeySiteEmail = "site_email"
	// KeySiteIcon 网站ico图片
	KeySiteIcon = "site_icon"
	// KeySiteName 网站名字
	KeySiteName = "site_name"
	// KeyCommentCheck 评论是否需要审核
	KeyCommentCheck = "comment_check"
	// KeyToolNotice 公告栏卡片说明信息
	KeyToolNotice = "tool_notice"
	// KeyUserListCount 用户管理界面显示用户数
	KeyUserListCount = "user_list_count"
	// KeyWebText 网站的二级标题
	KeyWebText = "web_text"
	// KeyWechat 微信收款码地址
	KeyWechat = "wechat"
	// KeyAlipay 支付宝收款码地址
	KeyAlipay = "alipay"
	// KeyNoFace 用户没上传头像的默认头像
	KeyNoFace = "no_face"
	// KeyMoeImg 个人导航界面的背景图片
	KeyMoeImg = "moe_img"
	// KeyWechatMiniProgramId 小程序appID
	KeyWechatMiniProgramId = "wechat_mini_program_id"
	// KeyWechatMiniProgramSecret 小程序秘钥
	KeyWechatMiniProgramSecret = "wechat_mini_program_secret"

	// KeyImgBedAddr chevereto图床地址
	KeyImgBedAddr = "img_bed_addr"
	// KeyImgLypBedAddr lskypro图床地址
	KeyImgLypBedAddr = "img_lyp_bed_addr"
	// KeyImgLypBedUser lskypro邮箱
	KeyImgLypBedUser = "img_lyp_user"
	// KeyImgLypBedPassword lskypro密码
	KeyImgLypBedPassword = "img_lyp_password"
	// KeyImgLypBedToken lskypro登录后的token信息
	KeyImgLypBedToken = "img_lyp_token"
	// KeyImgBedUpload 开始图床上传功能
	KeyImgBedUpload = "img_bed_upload"
	// KeySiteApiServer api服务地址
	KeySiteApiServer = "site_api_server"
	// KeySmtpUser 邮件服务器用户名
	KeySmtpUser = "smtp_user"
	// KeySmtpPass 邮件服务器密码(QQ邮箱填授权码)
	KeySmtpPass = "smtp_pass"
	// KeySmtpServer 邮件服务器发信服务器
	KeySmtpServer = "smtp_server"
	// KeySmtpPort 邮件服务器发信端口
	KeySmtpPort = "smtp_port"
	// KeySmtpName 邮件服务器发信名称
	KeySmtpName = "smtp_name"
	// KeyUrlRedirectOpen 开启文章网址跳转
	KeyUrlRedirectOpen = "url_redirect_open"
	// KeyUrlRedirectBackground 默认网址跳转背景
	KeyUrlRedirectBackground = "url_redirect_background"
	// KeyWechatMiniProgramPrice 微信小程序赞赏二维码
	KeyWechatMiniProgramPrice = "wechat_mini_program_price"
	// KeyWechatMiniProgramHeadImage 微信小程序我的界面头部图片
	KeyWechatMiniProgramHeadImage = "wechat_mini_program_head_image"
	// KeyWechatMiniProgramAbout 关于作者界面展示的内容
	KeyWechatMiniProgramAbout = "wechat_mini_program_about"
	// KeyWechatMiniProgramAnimation 是否显示我的追番
	KeyWechatMiniProgramAnimation = "wechat_mini_program_animation"
	// KeyWechatMiniProgramFriend 是否显示友链界面
	KeyWechatMiniProgramFriend = "wechat_mini_program_friend"
	// KeyWechatMiniProgramDonate 是否显示赞助界面
	KeyWechatMiniProgramDonate = "wechat_mini_program_donate"
	// KeyWechatMiniProgramDouBan 是否显示豆瓣
	KeyWechatMiniProgramDouBan = "wechat_mini_program_dou_ban"
	// KeyWechatMiniProgramComment 是否显示评论
	KeyWechatMiniProgramComment = "wechat_mini_program_comment"
	// KeyWechatMiniProgramPostBar 是否显示文章底部工具条
	KeyWechatMiniProgramPostBar = "wechat_mini_program_post_bar"
	// KeyTimeTaskSyncDouBan 是否每日同步豆瓣数据
	KeyTimeTaskSyncDouBan = "time_task_sync_dou_ban"
	// KeyTimeTaskSyncMusic163 是否每日同步网易云歌单
	KeyTimeTaskSyncMusic163 = "time_task_sync_music163"
	// KeyChatRoomAvatar 聊天室公共频道头像
	KeyChatRoomAvatar = "chatroom_avatar"

	// KeyDatabaseBackup 数据库备份
	KeyDatabaseBackup = "setting_database_backup"

	// KeySettingAppChat 是否显示聊天室
	KeySettingAppChat = "setting_app_chat"
	// KeySettingAppFriend 是否显示友链
	KeySettingAppFriend = "setting_app_friend"
	// KeySettingAppAnimation 是否显示追番
	KeySettingAppAnimation = "setting_app_animation"
	// KeySettingAppDonate 是否显示赞助
	KeySettingAppDonate = "setting_app_donate"
	// KeySettingAppDouBan 是否显示豆瓣
	KeySettingAppDouBan = "setting_app_dou_ban"
	// KeySettingAppMusic 是否显示音乐盒
	KeySettingAppMusic = "setting_app_music"
	// KeySettingAppDoc 是否显示文档
	KeySettingAppDoc = "setting_app_doc"
	// KeySettingAppProject 是否显示我的项目
	KeySettingAppProject = "setting_app_project"
	// KeySettingAppNavigation 是否显示个人导航
	KeySettingAppNavigation = "setting_app_navigation"
	// KeySettingAppLogin 登录界面背景
	KeySettingAppLogin = "setting_app_login"

	// KeySettingSideMoreDiary 显示日记
	KeySettingSideMoreDiary = "Key_setting_side_more_diary"
	// KeySettingSideMoreDonate 显示赞助博主
	KeySettingSideMoreDonate = "Key_setting_side_more_donate"
	// KeySettingSideMoreFriend 显示友链
	KeySettingSideMoreFriend = "Key_setting_side_more_friend"
	// KeySettingSideMoreAnimation 显示追番
	KeySettingSideMoreAnimation = "Key_setting_side_more_animation"
	// KeySettingSideMoreBarrage 显示弹幕留言墙
	KeySettingSideMoreBarrage = "Key_setting_side_more_barrage"
	// KeySettingSideMoreDouBan 显示豆瓣
	KeySettingSideMoreDouBan = "Key_setting_side_more_dou_ban"
	// KeySettingSideMoreProject 显示我的项目
	KeySettingSideMoreProject = "Key_setting_side_more_project"

	// KeySettingSideInfoLeft 左边侧边栏信息
	KeySettingSideInfoLeft = "key_setting_side_info_left"
	// KeySettingSideInfoRight 右边侧边栏信息
	KeySettingSideInfoRight = "key_setting_side_info_right"
	// KeySettingNavInfo 顶部导航栏信息
	KeySettingNavInfo = "key_setting_nav_info"

	// KeySettingUserDomainID 用户ID，用于域名验证
	KeySettingUserDomainID = "key_setting_user_domain"
)
